[[language]]
name = "python"
auto-format = true

formatter = { command = "ruff", args = ["format", "-"] }

language-servers = [
  "ruff",
  "basedpyright",
  "pyrefly"
]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]
